# Generated by Django 3.2.9 on 2022-06-28 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_courses_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='school/images/'),
            preserve_default=False,
        ),
    ]
