# Generated by Django 3.2.9 on 2022-07-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegCourses',
            fields=[
                ('field_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('registered_course', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisteredCourses',
        ),
    ]
